name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: ["8", "11", "16"]
    name: Java ${{ matrix.Java }} shadowJar
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java }}
      - name: Build shadow jar
        run: ./gradlew shadowJar
      - name: Run application
        run: java -jar build/libs/aliyun-geoip-nginx-all.jar
